version: "3.8"
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/sql/001_pgvector.sql:/docker-entrypoint-initdb.d/001_pgvector.sql:ro

  temporal:
    image: temporalio/auto-setup:1.25
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    depends_on: [postgres]
    ports: ["7233:7233"]

  temporal-ui:
    image: temporalio/ui:2.31.0
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports: ["8080:8080"]
    depends_on: [temporal]

  opa:
    image: openpolicyagent/opa:latest
    command: ["run", "--server", "/policies"]
    volumes:
      - ./infra/opa/policies:/policies:ro
    ports: ["8181:8181"]

  gateway:
    build: ./packages/gateway
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPA_URL=${OPA_URL}
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS}
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
    ports: ["3001:3001"]
    depends_on: [temporal, opa]

  worker:
    build: ./packages/worker
    environment:
      - NODE_ENV=development
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS}
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
    depends_on: [temporal]

  rag-service:
    build: ./packages/rag-service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports: ["8001:8001"]
    depends_on: [postgres]

  telephony-bridge:
    build: ./packages/telephony-bridge
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports: ["3003:3003"]

  ui-web:
    build: ./packages/ui-web
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:3001
    ports: ["3000:3000"]
    depends_on: [gateway]

volumes:
  pgdata:
